[package]
name = "pir2c"
version = "0.1.0"
edition = "2021"
keywords = ["embedded-hal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"
failure = "0.1"
