[package]
name = "pir2c"
version = "0.1.0"
edition = "2021"
keywords = ["embedded-hal"]

[dependencies]
thiserror = "1"
pretty-hex = "0.3"

serial-core = "0.4"


[dev-dependencies]
anyhow = "1"
serial = "0.4"
argh = "0.1"
